function Ehat = spec_out (wave, sqft)
%% function Ehat = spec_out (wave, sqft)
% Compute power spectral density (PSD).
%
% Inputs: 
%        wave is struct of wavemubers generated by spec_init.m; 
%        sqft is the square modulo of Fourier transform.
%
% Ouputs:
%        Ehat is 1D array of PSD.
%
% Written by Long Li 2020-08-10.
%

sqft = sqft(:);

% Power spectral density (PSD)
dk = wave.k1(2) - wave.k1(1);
Ehat = 0.*wave.k1;
for i = 1:length(wave.k1)
    % Lower bound of rings
    kmin = wave.k1(i) - dk/2;
    % Upper bound of rings
    kmax = wave.k1(i) + dk/2;
    % Integrate over rings 
    idk = find( (wave.k2 >= kmin) & (wave.k2 <= kmax) ); 
    Ehat(i) = sum(sqft(idk));
end

% Normalize
Ehat = wave.kfac.*Ehat;

end